apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: NFO_BASE_URL
          value: "{{ .Values.env.NFO_BASE_URL }}"
        - name: RAPP_URL
          value: "{{ .Values.env.RAPP_URL }}"
        - name: INFLUXDB_URL
          value: "{{ .Values.env.INFLUXDB_URL }}"
        - name: INFLUXDB_TOKEN
          value: "{{ .Values.env.INFLUXDB_TOKEN }}"
        - name: INFLUXDB_ORG
          value: "{{ .Values.env.INFLUXDB_ORG }}"
        - name: INFLUXDB_BUCKET
          value: "{{ .Values.env.INFLUXDB_BUCKET }}"
        - name: ADB_MACHINE_SSH_HOST
          value: "{{ .Values.env.ADB_MACHINE_SSH_HOST }}"
        - name: ADB_MACHINE_SSH_USER
          value: "{{ .Values.env.ADB_MACHINE_SSH_USER }}"
        - name: ADB_MACHINE_SSH_PASSWORD
          value: "{{ .Values.env.ADB_MACHINE_SSH_PASSWORD }}"
        - name: APP_ID
          value: "{{ .Values.environment.appId }}"
        - name: SME_DISCOVERY_ENDPOINT
          value: "{{ .Values.environment.smeDiscoveryEndpoint }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: test-results
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: test-results
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
